# Site
title: "sn3akiwhizper's glob"
name: 'sn3akiwhizper'
description: 'digital garden for a netizen who plays games, reads about things, and rambles about random topics.'
logo: 'assets/images/logo.png'
favicon: 'assets/images/favicon.ico'
baseurl: ''
disqus: 'TODO'
email: 'nicetry@nunya.biz'
mailchimp-list: 'https://todo.com'

include: ["_pages",]
permalink: /:title/
excerpt_separator: <!--excerpt-->
page_excerpts: true

twitter:
  username: sn3akiwhizper
  card: summary

social:
  name: sn3akiwhizper
  links:
    - https://twitter.com/sn3akiwhizper
    - https://github.com/sn3akiwhizper
    - https://youtube.com/@sn3akiwhizper
    - https://tiktok.com/@sn3akiwhizper
    - https://twitch.tv/sn3akiwhizper
    - https://patreon.com/sn3akiwhizper
    - https://sn3akiwhizper.github.io

google_site_verification: ???
locale: "en_US"
timezone: "America/Chicago"

authors:
    sn3akiwhizper:
      name:           sn3akiwhizper
      site:           https://sn3akiwhizper.github.io
      avatar:         /assets/images/avatar1.jpg
      bio:            "I'm sn3akiwhizper and I play videogames, develop software, and read things."
      email:          nicetry@nunya.biz

# Defaults
defaults:
  # all posts
  - scope:
      path: "_posts"
    values:
      layout: post
      author: sn3akiwhizper
      avatar: /assets/images/avatar1.jpg
      
  # all pages
  - scope:
      path: "_pages"
    values:
      layout: page

##########################################################################################
##########################################################################################

# Plugins
plugins: 
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-tagging-related_posts
  - jekyll-responsive-image
  - jekyll-namespaces
  - jekyll-wikilinks
  - jekyll-graph
  - jekyll-youtube
  - jemoji
  - jekyll-timeago
  - liquid_reading_time

##########################################################################################
##########################################################################################
#jemoji plugin config
#can create custom emoji, see here: https://github.com/github/gemoji

# emoji:
#   src: "/assets/images/emoji"

##########################################################################################
##########################################################################################
#jekyll-timeago plugin config

jekyll_timeago:
  default_locale: 'en'

##########################################################################################
##########################################################################################
#jekyll-wikilinks plugin config

wikilinks:
  attributes:
    enabled: true
  css:
    exclude: []
    name:
      typed: 'typed'
      wiki: 'wiki-link'
      web: 'web-link'
      invalid_wiki: 'invalid-wiki-link'
      embed_container: 'embed-container'
      embed_title: 'embed-title'
      embed_content: 'embed-content'
      embed_link: 'embed-wiki-link'
      embed_image_container: 'embed-image-container'
      embed_image: 'embed-image'
  enabled: true
  exclude: []

##########################################################################################
##########################################################################################
#jekyll-graph plugin config

graph:
  enabled: true
  exclude: []
  path:
    assets: "/assets"
    scripts: "/assets/js"
  net_web:
    enabled: true
    exclude:
      attrs: false
      links: false
    force:
      charge: -300
      strength_x: 0.3
      x_val: 0.75
      strength_y: 0.1
      y_val: 0.9
  tree:
    dag_lvl_dist: 100
    enabled: true
    force:
      charge: -100
      strength_x: 0.3
      x_val: 0.9
      strength_y: 0.1
      y_val: 0.9

##########################################################################################
##########################################################################################
#jekyll-responsive-image plugin config

responsive_image:
  # [Required]
  # Path to the image template.
  template: _includes/responsive-image.html

  # [Optional, Default: 85]
  # Quality to use when resizing images.
  default_quality: 90

  # [Optional, Default: []]
  # An array of resize configuration objects. Each object must contain at least
  # a `width` value.
  sizes:
    - width: 480  # [Required] How wide the resized image will be.
      quality: 80 # [Optional] Overrides default_quality for this size.
    - width: 800
    - width: 1400
      quality: 90

  # [Optional, Default: false]
  # Rotate resized images depending on their EXIF rotation attribute. Useful for
  # working with JPGs directly from digital cameras and smartphones
  auto_rotate: false

  # [Optional, Default: false]
  # Strip EXIF and other JPEG profiles. Helps to minimize JPEG size and win friends
  # at Google PageSpeed.
  strip: false

  # [Optional, Default: assets]
  # The base directory where assets are stored. This is used to determine the
  # `dirname` value in `output_path_format` below.
  base_path: assets

  # [Optional, Default: assets/resized/%{filename}-%{width}x%{height}.%{extension}]
  # The template used when generating filenames for resized images. Must be a
  # relative path.
  #
  # Parameters available are:
  #   %{dirname}     Directory of the file relative to `base_path` (assets/sub/dir/some-file.jpg => sub/dir)
  #   %{basename}    Basename of the file (assets/some-file.jpg => some-file.jpg)
  #   %{filename}    Basename without the extension (assets/some-file.jpg => some-file)
  #   %{extension}   Extension of the file (assets/some-file.jpg => jpg)
  #   %{width}       Width of the resized image
  #   %{height}      Height of the resized image
  #
  output_path_format: assets/resized/%{width}/%{basename}

  # [Optional, Default: true]
  # Whether or not to save the generated assets into the source folder.
  save_to_source: false

  # [Optional, Default: false]
  # Cache the result of {% responsive_image %} and {% responsive_image_block %}
  # tags. See the "Caching" section of the README for more information.
  cache: false

  # [Optional, Default: []]
  # By default, only images referenced by the responsive_image and responsive_image_block
  # tags are resized. Here you can set a list of paths or path globs to resize other
  # images. This is useful for resizing images which will be referenced from stylesheets.
  extra_images:
    - assets/foo/bar.png
    - assets/bgs/*.png
    - assets/avatars/*.{jpeg,jpg}

##########################################################################################
##########################################################################################
#jekyll-feed plugin config

feed:
  # path: /blog/feed.atom #if /feed.xml is already taken
  categories:
    - news
    - updates
  posts_limit: 10
  excerpt_only: true
  disable_in_development: true

##########################################################################################
##########################################################################################

# Syntax
markdown: kramdown
highlighter: rouge

# Paginate
paginate: 10

# Exclude metadata and development time dependencies (like Grunt plugins)
exclude: [README.markdown, package.json, grunt.js, Gruntfile.js, Gruntfile.coffee, node_modules, Rakefile]
